version: "3"

services:
  nc:
    image: nextcloud:apache
    ports:
      - 8000:80
    volumes:
      - nc_data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=nextcloudpassword
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<password_postgres>
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    expose:
      - 5432

volumes:
  nc_data:
  db_data:
